apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-gateway

resources:
  - 01-namespace.yaml
  - 02-gateway-class-config.yaml
  - 03-gateway-class.yaml
  - 04-gateway.yaml
