apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piraeus-datastore

resources:
  - 01-cluster.yaml
  - 02-database-satellite-config.yaml
  - 03-database-storage-class.yaml
  - 04-replicated-database-storage-class.yaml
