apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibaship
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: "30s"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kibamail/kibaship.git
    targetRevision: HEAD
    path: clusters/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
